import React, { useState } from 'react';
import { useSchemaStore } from '../../store/useSchemaStore';
import type { SchemaGraph } from '../../types/schema.types';

function generateMarkdown(graph: SchemaGraph): string {
  let md = `# Database Schema Documentation\n\n`;
  md += `> Auto-generated by MongoLens\n\n`;

  md += `## Collections Overview\n\n`;
  md += `| Collection | Fields | Indexes | Outgoing Refs |\n`;
  md += `|------------|--------|---------|---------------|\n`;
  graph.collections.forEach((col) => {
    const outRefs = graph.relations.filter((r) => r.from === col.name).length;
    md += `| **${col.name}** | ${col.fields.length} | ${col.indexes.length} | ${outRefs} |\n`;
  });
  md += `\n---\n\n`;

  graph.collections.forEach((col) => {
    md += `### 📦 \`${col.name}\`\n\n`;
    if (graph.deadCollections.includes(col.name)) {
      md += `> **⚠️ Warning:** This collection is unreferenced (dead).\n\n`;
    }

    md += `**Fields**\n\n`;
    md += `| Name | Type | Required | Notes |\n`;
    md += `|------|------|----------|-------|\n`;
    col.fields.forEach((f) => {
      const typeStr = f.isArray ? `[${f.type}]` : f.type;
      const reqStr = f.required ? '✅' : '';
      const notes = [];
      if (f.ref) notes.push(`→ \`${f.ref}\``);
      if (f.unique) notes.push('Unique');
      md += `| \`${f.name}\` | \`${typeStr}\` | ${reqStr} | ${notes.join(', ')} |\n`;
    });
    md += `\n`;

    if (col.indexes.length > 0) {
      md += `**Indexes**\n\n`;
      col.indexes.forEach((idx) => {
        const fields = Object.entries(idx.fields)
          .map(([k, v]) => `\`${k}\`: ${v}`)
          .join(', ');
        const opts = [];
        if (idx.options?.unique) opts.push('Unique');
        if (idx.options?.sparse) opts.push('Sparse');
        md += `- { ${fields} } ${opts.length > 0 ? `*(${opts.join(', ')})*` : ''}\n`;
      });
      md += `\n`;
    }
    md += `---\n\n`;
  });

  return md;
}

function generateTypeScript(graph: SchemaGraph): string {
  let ts = `// Auto-generated by MongoLens\n`;
  ts += `// Types corresponding to your Mongoose schemas\n\n`;

  const typeMap: Record<string, string> = {
    String: 'string',
    Number: 'number',
    Boolean: 'boolean',
    Date: 'Date',
    ObjectId: 'string', // or Types.ObjectId
    Buffer: 'Buffer',
    Mixed: 'any',
  };

  graph.collections.forEach((col) => {
    ts += `export interface I${col.name} {\n`;
    col.fields.forEach((f) => {
      let tsType = typeMap[f.type] || 'any';
      if (f.ref) {
        // Option to type refs as either string ID or populated interface
        tsType = `string | I${f.ref}`;
      }
      if (f.isArray) {
        tsType = `Array<${tsType}>`;
      }
      const optionalMark = f.required || f.name === '_id' ? '' : '?';
      ts += `  ${f.name}${optionalMark}: ${tsType};\n`;
    });
    ts += `}\n\n`;
  });

  return ts;
}

export default function CodeGenerator() {
  const { graph } = useSchemaStore();
  const [view, setView] = useState<'markdown' | 'typescript'>('markdown');
  const [copied, setCopied] = useState(false);

  const content =
    view === 'markdown' ? generateMarkdown(graph) : generateTypeScript(graph);

  const handleCopy = () => {
    navigator.clipboard.writeText(content).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', height: '100%', padding: '20px' }}>
      <div style={{ display: 'flex', alignItems: 'center', marginBottom: '16px', gap: '16px' }}>
        <h1 style={{ color: '#e2e8f0', fontSize: '20px', fontWeight: 700, margin: 0 }}>
          ⚡ Code & Docs Generator
        </h1>
        
        <div style={{ marginLeft: 'auto', display: 'flex', gap: '8px' }}>
          <div
            style={{
              background: '#0f172a',
              borderRadius: '6px',
              padding: '4px',
              display: 'flex',
              gap: '4px',
              border: '1px solid #1e293b'
            }}
          >
            <button
              onClick={() => setView('markdown')}
              style={{
                background: view === 'markdown' ? '#1e293b' : 'transparent',
                border: 'none',
                color: view === 'markdown' ? '#60a5fa' : '#64748b',
                padding: '6px 12px',
                borderRadius: '4px',
                cursor: 'pointer',
                fontSize: '12px',
                fontWeight: view === 'markdown' ? 600 : 400,
              }}
            >
              📝 Markdown
            </button>
            <button
              onClick={() => setView('typescript')}
              style={{
                background: view === 'typescript' ? '#1e293b' : 'transparent',
                border: 'none',
                color: view === 'typescript' ? '#3178c6' : '#64748b',
                padding: '6px 12px',
                borderRadius: '4px',
                cursor: 'pointer',
                fontSize: '12px',
                fontWeight: view === 'typescript' ? 600 : 400,
              }}
            >
              📘 TypeScript
            </button>
          </div>

          <button
            onClick={handleCopy}
            style={{
              background: '#10b981',
              border: 'none',
              color: '#022c22',
              padding: '6px 16px',
              borderRadius: '6px',
              cursor: 'pointer',
              fontSize: '13px',
              fontWeight: 700,
              display: 'flex',
              alignItems: 'center',
              gap: '6px',
              minWidth: '100px',
              justifyContent: 'center',
            }}
          >
            {copied ? '✅ Copied!' : '📋 Copy Text'}
          </button>
        </div>
      </div>

      <div
        style={{
          flex: 1,
          background: '#0a1628',
          border: '1px solid #1e293b',
          borderRadius: '8px',
          overflow: 'hidden',
          display: 'flex',
          flexDirection: 'column',
        }}
      >
        <div
          style={{
            padding: '8px 16px',
            background: '#0f172a',
            borderBottom: '1px solid #1e293b',
            color: '#64748b',
            fontSize: '11px',
            fontFamily: 'monospace',
          }}
        >
          {view === 'markdown' ? 'schema-docs.md' : 'schema.types.ts'}
        </div>
        <textarea
          readOnly
          value={content}
          style={{
            flex: 1,
            width: '100%',
            background: 'transparent',
            border: 'none',
            color: '#e2e8f0',
            padding: '16px',
            fontFamily: 'monospace',
            fontSize: '13px',
            lineHeight: 1.5,
            resize: 'none',
            outline: 'none',
          }}
        />
      </div>
    </div>
  );
}
